services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./backend/media:/usr/src/app/media
      - ./backend/staticfiles:/usr/src/app/staticfiles
      - ./backend/collected_static:/usr/src/app/collected_static
      - ./backend/logs:/usr/src/app/logs
    environment:
      - DB=db
#    expose:
#      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend


  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    env_file:
      - ./frontend/.env
    container_name: frontend
    restart: always
    expose:
      - "3000"

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - db

networks:
  backend:
    driver: bridge
  db:
    driver: bridge